services:
  backend:
    container_name: mamfachowca_docker-backend
    build: ./backend
    ports:
      - "8000:80"  # host:container
    #volumes:
    #  - ./backend:/var/www/html
    working_dir: /var/www/html
    env_file:
      - ./backend/.env.docker
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: mamfachowca_docker-database
    platform: "linux/amd64"
    image: mysql:5.7
    env_file:
      - ./backend/.env.docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root    
    networks:
      - app-network  

  frontend:
    container_name: mamfachowca_docker-frontend
    build: ./frontend
    ports:
      - "8080:8080" # domyślny port Vite
    env_file:
      - ./frontend/.env.docker
    working_dir: /app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
